# This file was generated by GoReleaser. DO NOT EDIT.
cask "higgs" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "582cf36ce4bfd25ab91b1e5bf21862aff8262502f3b46267331ade85741cdd78"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
    on_intel do
      sha256 "a9cd236fcf6a0730412e55767a3dee379f731fc97017b5c6443964c3080d3649"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
  end
  on_linux do
    on_arm do
      sha256 "55cc52b78778970e97a694be9a5938700abea0e55e28440e59c39ebaa0555fd8"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
    on_intel do
      sha256 "2d615ef9872ed4c8eaf8a32d6b1131661e38bf8d04a7882dca65d61272fe5f74"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
  end

  name "higgs"
  desc "Agent-first CLI for Proton Mail with schema, NDJSON and typed errors"
  homepage "https://github.com/higgscli/higgs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "higgs"

  # No zap stanza required
end
