# This file was generated by GoReleaser. DO NOT EDIT.
cask "higgs" do
  version "1.2.5"

  on_macos do
    on_intel do
      sha256 "1967926619fe14206d2f7ce91f5bd0f388864e2853c90512196cf5d12dfcf844"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
    on_arm do
      sha256 "e74ea44f8c28a50080eddcdb83ca5b16f4642f1d24d0336b56d06ffb43b9b6bb"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
  end

  on_linux do
    on_intel do
      sha256 "273c14731c4634a98020abc85691747a159401f59b287706d9e4b9b7b33744fc"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
    on_arm do
      sha256 "e3213c5b471ded0183e5dbcf243f56cc3e23dda88f392615a664230a5edf54ad"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/higgscli/higgs/"
    end
  end

  name "higgs"
  desc "Agent-first CLI for Proton Mail with schema, NDJSON and typed errors"
  homepage "https://github.com/higgscli/higgs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "higgs"

  # No zap stanza required

end
