# This file was generated by GoReleaser. DO NOT EDIT.
cask "higgs" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "7b1bdb3472974949fadf103c67a249b8136ec2802b643c8b2e2927405cb3f23d"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d40a1823e486d588c03eab998c594cbb0ac3f484092c9eff7879cc81d6515316"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d5c781b82ca4a78d10464a09d62b5b2719c5661df24825d96e2b510a30fef359"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8372a406746a5c1fd529e6a0de1b59aedbb2a4a2e1ec03d0d1aab3fe76cc8033"
      url "https://github.com/higgscli/higgs/releases/download/v#{version}/higgs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "higgs"
  desc "Agent-first CLI for Proton Mail with schema, NDJSON and typed errors"
  homepage "https://github.com/higgscli/higgs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "higgs"

  # No zap stanza required
end
