# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Higgs < Formula
  desc "Agent-first CLI for Proton Mail with schema, NDJSON and typed errors"
  homepage "https://github.com/higgscli/higgs"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/higgscli/higgs/releases/download/v1.2.0/higgs_1.2.0_darwin_amd64.tar.gz"
      sha256 "01a2a3bf8b8d8aece05c949e1a031980d345c57f355b5f7f620e3e11e881f0c5"

      define_method(:install) do
        bin.install "higgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/higgscli/higgs/releases/download/v1.2.0/higgs_1.2.0_darwin_arm64.tar.gz"
      sha256 "3701f739f5da2a556352cb5788275283b0bef4a898b0662df11b9e936ec35149"

      define_method(:install) do
        bin.install "higgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/higgscli/higgs/releases/download/v1.2.0/higgs_1.2.0_linux_amd64.tar.gz"
      sha256 "1f4f48d021a016fe3049a54201257b4a5e9f713fcc39e260cba915a4e652e303"
      define_method(:install) do
        bin.install "higgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/higgscli/higgs/releases/download/v1.2.0/higgs_1.2.0_linux_arm64.tar.gz"
      sha256 "1ddd90e36a804d7615a63002b8f881ab7f722054e692af19d3cfcd3c4ddde0f9"
      define_method(:install) do
        bin.install "higgs"
      end
    end
  end

  test do
    system "#{bin}/higgs", "--version"
  end
end
